#!/bin/sh
PORT=1035
APP="`basename $0`"
APPDIR="`dirname $0`"
GWT_DIR="${APPDIR}/lib"
MODE="c"
ARGS=""

function usage() {
    echo "Usage: ${APP} [-h|-d|-s|-g <GWT Directory>] [other options]"
    echo "  -h      This cruft"
    echo "  -d      Debug mode"
    echo "  -s      Shell mode"
    echo "  -g dir  Directory that GWT jar files are in"
    exit 1
}

while [ -n "$1" ]; do
    case "$1" in
        -s|--shell)
            MODE="s"
            ;;
        -d|--debug)
            MODE="d"
            ;;
        -g|--gwt)
            shift
            GWT_DIR=$1
            ;;
        -h|--help)
            usage
            ;;
        *)
            ARGS="${SRGS} $1"
            ;;
    esac
    shift
done

if [ -z "$GWT_DIR" ]; then
    usage
fi

if [ ! -f "${GWT_DIR}/gwt-user.jar" ]; then
    echo "GWT not found in '${GWT_DIR}'. Check your GWT install."
    exit 128
fi

CLASSPATH="${APPDIR}/src:${APPDIR}/bin:${GWT_DIR}/gwt-api-checker.jar:${GWT_DIR}/gwt-dev.jar:${GWT_DIR}/gwt-servlet-deps.jar:${GWT_DIR}/gwt-servlet.jar:${GWT_DIR}/gwt-soyc-vis.jar:${GWT_DIR}/gwt-user.jar:${GWT_DIR}/validation-api-1.0.0.GA-sources.jar:${GWT_DIR}/validation-api-1.0.0.GA.jar"

# -XstartOnFirstThread does not apear to work on Mac OS X. YMMV
# https://groups.google.com/forum/#!topic/google-web-toolkit/BMruUZDiTXk
case "$MODE" in
    s)
        exec java -cp "$CLASSPATH" com.google.gwt.dev.GWTShell $ARGS org.tritarget.CipherEncoder/CipherEncoder.html
        ;;
    d)
        echo "Running debug server on port ${PORT}."
        exec java -Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=$PORT -cp "$CLASSPATH" com.google.gwt.dev.GWTShell -logLevel DEBUG $ARGS org.tritarget.CipherEncoder/CipherEncoder.html
        ;;
    *)
        exec java -cp "$CLASSPATH" com.google.gwt.dev.Compiler $ARGS org.tritarget.CipherEncoder
        ;;
esac
