#!/bin/sh
APPDIR=`dirname $0`;
java -XstartOnFirstThread -cp "$APPDIR/src:$APPDIR/bin:/Users/suki/source/gwt-mac-1.4.62/gwt-user.jar:/Users/suki/source/gwt-mac-1.4.62/gwt-dev-mac.jar" com.google.gwt.dev.GWTCompiler -out "$APPDIR/www" "$@" com.tritarget.CipherEncoder;
